### ISSUE TITLE
Peer-to-peer-code-review

### ISSUE THREAD

**Issue by anita00001** [sawmon71293/ToDoList#12]
Reviewer: @anita00001 @Tshobohwa @baqar-abbas

## Highlights
- Good use of CSS Framework: Bootstrap
- Good use of CSS selectors
- No linter errors
- Clean and readable code

## Suggestions
- [ ] We have noticed some commits have linter errors, and you fixed them later in another commit. You can check for the linters on your local machine before making any commits.
- [ ] We have noticed that you have three functions in index.js which can have different modules. Having separate modules for different functions has benefits like clean and readable code, ease to modify and debugging, and so on.

**Comment by sawmon71293** [comment]
Thanks for your professional review, guys. I really appreciated. I have fixed all of those.
